#!/usr/bin/env bash

# https://go.dev/doc/install

VERSION="1.24.3"
FILENAME="go${VERSION}.linux-amd64"

curl -LO https://go.dev/dl/${FILENAME}.tar.gz
sudo rm -rf /usr/local/go
sudo tar -C /usr/local -xzf ${FILENAME}.tar.gz

rm ${FILENAME}.tar.gz
