#!/usr/bin/env bash

# https://github.com/neovim/neovim/blob/master/INSTALL.md

VERSION="v0.11.2"
FILENAME="nvim-linux-x86_64"

curl -LO https://github.com/neovim/neovim/releases/download/${VERSION}/${FILENAME}.tar.gz
sudo rm -rf /opt/nvim
sudo tar -C /opt -xzf ${FILENAME}.tar.gz
sudo mv /opt/${FILENAME} /opt/nvim
sudo ln -sf /opt/nvim/bin/nvim /usr/local/bin/nvim

rm nvim-linux-x86_64.tar.gz
