#!/usr/bin/env bash

TARGET_OS=""
GREP=""

usage () {
  echo "Usage: sudo $0 [grep]"
}

if [ "$(id -u)" -ne 0 ]; then
  echo "Must run as root"
  usage
  exit 1
fi

if [[ "$#" -gt 1 ]]; then
  usage
  exit 1
elif [[ "$#" -eq 1 ]]; then
  GREP="$1"
fi

KERNEL=$(uname -s)
case "$KERNEL" in
  Linux*)
    TARGET_OS="linux"
    ;;
  Darwin*)
    TARGET_OS="mac"
    ;;
  *)
    echo "Error: unsupported operating system"
    exit 1
    ;;
esac

log () {
  echo "[RUN] $1"
}

log "TARGET_OS: $TARGET_OS, GREP: $GREP"
log "======================================================================"
log "COPYING HOME"
log "======================================================================"

log "stow -D home -t ~/"
stow -D home -t ~/

log "stow home -t ~/"
stow home -t ~/

log "======================================================================"
log "RUNNING SCRIPTS"

scripts=$(find ./scripts/$TARGET_OS -mindepth 1 -maxdepth 1 -executable)

for script in $scripts; do
  if basename $script | grep -vq "$GREP"; then
    log "SKIPPING $script"
    continue
  fi

  log "RUNNING $script"
  log "======================================================================"
  $script
  log "======================================================================"
done

log "DONE!"
log "======================================================================"
